### ISSUE TITLE
Add existing importedprojects.md doc to website

### ISSUE THREAD

**Issue by rajivnathan** [eclipse/codewind-docs#54]
The importedprojects.md doc exists on the repo https://github.com/eclipse/codewind-docs/blob/master/docs/_documentations/importedprojects.md but appears to be missing from the docs website

Should probably have an importing projects doc and can link to it from https://www.eclipse.org/codewind/mdteclipsemanagingprojects.html

There also seems to be a in the `Import Project` bullet that seems a bit out of place since create isn't mentioned.

**Comment by micgibso** [comment]
@rajivnathan I've restored importedprojects.html and for now it's under Getting started.
@sishida fyi

**Comment by micgibso** [comment]
@rajivnathan Topic now entitled `Adding existing projects` and added to both Codewind in Eclipse and Codewind in VS Code sections, see PR #62 for final modifications.

**Comment by micgibso** [comment]
@rajivnathan I don't think it needs a link from mdteclipsemanagingprojects.html because it now appears in the new TOC as a separate entry, have a look at the latest and see what you think. 
Finally, your sentence above `There also seems to be a in the Import Project bullet that seems a bit out of place since create isn't mentioned.` is it missing something? There also seems to be a...?

**Comment by rajivnathan** [comment]
Thanks @micgibso these changes look great! I can't recall what the problem was wrt `Import Project` so clearly couldn't have been very important or might be fixed in changes since then. Either way I'm happy to close this issue now. Cheers
