### ISSUE TITLE
using a template repo link in docs returns 404

### ISSUE THREAD

**Issue by AndyRWatson** [eclipse/codewind-docs#9]
When using the landing page,  Following Configuring Codewind -> Using a template repository of your own link gives a 404

**Comment by sishida** [comment]
Hi, @AndyRWatson, I checked the landing pages today and was able to view the "Using a template repository of your own" page on the Safari and Chrome browsers: https://www.eclipse.org/codewind/usingadifferenttemplate.html

Are you using a different browser, or perhaps someone fixed the link after this issue was opened? Thanks!

**Comment by AndyRWatson** [comment]
Hi Sarah, I just checked the link again and now seems to be working
